### ISSUE TITLE
libtigergraph.so not found by loader

### ISSUE THREAD

**Issue by rom-burner** [DavidBakerEffendi/tigergraph#1]
in the container, ~/tigergraph/app/3.0.0/bin/libtigergraph.so is symlinked to ../dev/gdk/gsdk/lib/tg_3.0.5_dev/libtigergraph.so, which doesn't exist.  changing the symlink to ../dev/gdk/gsdk/lib/tg_3.0.0_dev/libtigergraph.so fixes it.

(oops edit: looks like this may be fixed by f660dd8ca61e0a0a7809f65b2c6ab12f7c974bcf, saw it too late and not had chance to pull updated container yet).

**Comment by DavidBakerEffendi** [comment]
Thanks! Yeah I removed a lot of stuff from a Dockerfile Bruno Simic from TigerGraph shared with me but it had a few bugs so I rolled them back in my latest commits. He recently gave me a fixed version which I'll look at investigating and testing to see if it works (since it originally saved a bunch more space).
